<div class="row">
    <div class="span3" id="left-bar">
    	<h1 class="testimonial-title"> Testimonials </h1>
      	<blockquote class="testominal" id="testimony-box"><p class="testimony-box-content">"A big surprise and a great start to the week. I thought it was scam until I got a confirmation that I have won. Got the credit really quickly and thank you."</p><p><small> Chinedu from Aba</small></p></blockquote>
       	<blockquote class="testominal" id="testimony-box"><p class="testimony-box-content">"I just wanted to say a huge thanks for the credit, it went a long way."</p><p><small> Kenny from Ikeja</small></p></blockquote>
      	<blockquote class="testominal" id="testimony-box"><p class="testimony-box-content">"Thank you for the #1000 airtime, the credit came at the right time. I was able to call the people that matters when my wife was in labour and I needed to call for help in the middle of night"</p><p><small> Ahmed from Ikotun </small></p></blockquote>
      	<blockquote class="testominal" id="testimony-box"><p class="testimony-box-content">"I never believe I can win anything, when I heard about a site where I can win free credit I thought it was a scam. The #750 credit went a long way."</p><p><small> Dotun from Ekiti </small></p></blockquote>
    </div>
    <div class="span9" id="right-bar">
    		<h1 class="main-title"> Frequently Asked Questions </h1>
  
          <p class="main-content"> <b> What is MylgCharity? </b> </p>

      <p class="main-content"> It's an organisation that is committed to eradicating poverty by giving back to the community. You win airtime by just registering you don't have to buy tickets. You just enter your Number and if it is drawn you win Airtime. You will a grand prize every month by playing with just #100 You can only collect by visiting the site, but don't worry, a daily email is sent to remind you. Rules of the Free Postcode Lottery. </p>

      <p class="main-content"> <b> If I win how do I claim? </b> </p>

      <p class="main-content"> A large 'Collect' button appears. </p>

      <p class="main-content"> <b> What if I didn’t log in to claim my Airtime? </b> </p>

      <p class="main-content"> Our daily email will serve as reminder to check in case you have won some Airtime </p>

      <p class="main-content"> <b> How is the postcode chosen? </b> </p>

      <p class="main-content"> It is selected randomly by the computer from the list of all Numbers entered. </p>

      <p class="main-content"> <b> When is the draw? </b> </p>

      <p class="main-content"> The Jackpot draw is at noon every day and for the grand prize this is done every end of the Month. </p>

      <p class="main-content"> <b> Do I have to re-enter each draw? </b> </p>

      <p class="main-content"> No. Once you have entered once, you will be entered every day to win daily Airtime but for the monthly grand prize you need to enter every month. You will still need to check the site to see if you have won though. </p>

      <p class="main-content"> <b> How can it be free to enter? </b> </p>

      <p class="main-content"> The prize money will be generated by ad revenue on the site, which is itself generated by the traffic caused by users checking the draw to see if they've won. Also it is part of given back to the community as every little helps. Money raised from the Grand prize goes to our charity which helps provide bore holes and other social amenities to any selected Local Government </p>

      <p class="main-content"> <b> How do I collect if I win? </b> </p>

      <p class="main-content"> If your Number is drawn you will get a notification via email. </p>

      <p class="main-content"> <b> Can I register more than once? </b> </p>

      <p class="main-content"> No. In order to keep it fair we insist that you only register one email and Number. Anyone found breaking this rule will be permanently disqualified from playing. We constantly monitor entries and may disqualify suspicious entries without notifying you. </p>

      <p class="main-content"> <b> Can I register on someone else's behalf? </b> </p>

      <p class="main-content"> No, whilst that would be very kind of you to do so we cannot allow this as this leave the site open to abuse and we cannot allow users to register other people's personal data onsite. If you would like someone to enter please ask them to do so themselves. Again, anyone found breaking this rule will be permanently disqualified from playing. </p>

      <p class="main-content"> <b> Why doesn't my Number ever win? </b> </p>

      <p class="main-content"> The draw is random from all those that are entered. There is no geographical bias. It may seem like the draw favours some local government or an area over others but it is just the luck of the draw. </p>

      <p class="main-content"><b> How do I know this isn't a scam? </b> </p>

      <p class="main-content"> There are hundreds of testimonials from winners. </p>

      <p class="main-content"> <b> What's in it for us? </b> </p>

      <p class="main-content">Any money that we make in excess of the money that we give away goes towards grand prize and community development in a selected local government. The costs of hosting the site and the time spend answering questions for people who can't be bothered to read the FAQs (Well done by the way!)
                </p>
  		</div>	
	
</div>